language: node_js
sudo: false
node_js:
  - '6'
env:
  - CI_SERVER=1
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - mongo --version
  - mkdir -p data/db
  - 'mongod --dbpath=data/db &'
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - mongo --eval 'db.hostInfo()'
script:
  - npm test
after_script:
  - npm run coverage
  - coveralls < coverage/lcov.info

deploy:
  - skip_cleanup: true
    provider: npm
    email: admin@sierrasoftworks.com
    tag: next
    api_key:
      secure: A2tBD6QCdYd814GqbVNmVFzQjbAFF+4CK6JhOJEG3ovXwXuVbIlm+tSu6u+/zIS7ChTJ+RDKsY0/AlMrrhP4Qbm8pd0MsGNWMDPelklDXKHj8tw/s3FdXi8bU2Kn8IGAwMY729MMGdShvMbKx71Wt20jPQ/cMf2Bz25j4Q3WEMQ=
    on:
      condition: $TRAVIS_BRANCH =~ alpha|beta
      repo: SierraSoftworks/Iridium
  - skip_cleanup: true
    provider: npm
    email: admin@sierrasoftworks.com
    api_key:
      secure: A2tBD6QCdYd814GqbVNmVFzQjbAFF+4CK6JhOJEG3ovXwXuVbIlm+tSu6u+/zIS7ChTJ+RDKsY0/AlMrrhP4Qbm8pd0MsGNWMDPelklDXKHj8tw/s3FdXi8bU2Kn8IGAwMY729MMGdShvMbKx71Wt20jPQ/cMf2Bz25j4Q3WEMQ=
    on:
      condition: '! $TRAVIS_BRANCH =~ alpha|beta'
      repo: SierraSoftworks/Iridium
